### ISSUE TITLE
"Ambiguous class resolution" when installing on standard Laravel application.

### ISSUE THREAD

**Issue by Sn0wCrack** [ProjektGopher/whisky#11]
Not entirely an issue since none of the code in this repository needs to be loaded in, but this warning does get generated when installing Whisky over the standard laravel/laravel template that also uses the "App" namespace:

```
Warning: Ambiguous class resolution, "App\Providers\AppServiceProvider" was found in both "/home/vagrant/project/app/Providers/AppServiceProvider.php" and "/home/vagrant/project/vendor/projektgopher/whisky/app/Providers/AppServiceProvider.php", the first will be used.
```

**Comment by ProjektGopher** [comment]
That's really interesting. I'd never even considered that possibility (which like you say isn't really a huge issue cause it's never loaded). I might change the namespace regardless. Thx for pointing it out

**Comment by ProjektGopher** [comment]
I'll take a look at it and see what I can figure out
