### ISSUE TITLE
[Windows Support] Install Command - chmod not recognized

### ISSUE THREAD

**Issue by ProjektGopher** [ProjektGopher/whisky#12]
- `whisky install`
 ```
 Creating whisky.json in project root...
'chmod' is not recognized as an internal or external command,
operable program or batch file.
'chmod' is not recognized as an internal or external command,
operable program or batch file.
Git hooks installed successfully.
```

**Comment by gpibarra** [comment]
this can be easily done using the new [Whiskey::isWindows()](https://github.com/ProjektGopher/whisky/blob/main/app/Whisky.php#L69) method.
It will depend if you use that function or the Platform one [app/Platform.php](https://github.com/ProjektGopher/whisky/pull/22/files#diff-29d82da8ec0abe94ae9bfd26d1accf1afa23ff4897280efcd5d6686ccd76eeb4)
However, this warning does not prevent it from working on windows.

**Comment by ProjektGopher** [comment]
When I'm able to finish my refactoring I'll be using the Platform classes method. This should be an easy win
