### ISSUE TITLE
can't build on `Windows`

### ISSUE THREAD

**Issue by faissaloux** [ProjektGopher/whisky#56]
The app builds well on Linux but when I try building it on Windows for testing/developing I got an error related to `SIGINT` and it is coming from `laravel-zero/framework`, when I checked it I found that they have fixed it on [PR](https://github.com/laravel-zero/framework/pull/479), but not yet released.

`laravel-zero/framework` needs a bump, I'll wait for the release to do it.

**Comment by ProjektGopher** [comment]
Interesting edge case. I ran into Process Control functions for the first time a couple weeks ago when I had to run my own cleanup code before a vapor job timed out on the queue. I've still gotta write an article about that solution

**Comment by faissaloux** [comment]
Definitely, that would help a lot of devs on same situation. 👌🏻

**Comment by ProjektGopher** [comment]
We might be able to just not worry about this for whisky though, since it's realistically only ever going to be built by me when it's versioned and published
