### ISSUE TITLE
[Not issue] - commitlint

### ISSUE THREAD

**Issue by davideprevosto** [ProjektGopher/whisky#64]
Hi, that's not an issue. 
I searched for a way to run `commitlint` using whisky without luck.

My whisky.json is:

```
{
  "disabled": [],
  "hooks": {
    "pre-commit": [
      "npx --no -- commitlint --edit ${1}",
      "composer format",
      "bash ./local/pre-commit/prettier.sh",
      "bash ./local/pre-commit/stylelint.sh"
    ],
    "pre-push": [
      "composer test"
    ]
  }
}
```

I am getting the following errors. I am 100% missing something, but I can't get it.

```
/Users/dev/local.test/node_modules/@commitlint/cli/lib/cli.js:123
        throw err;
        ^

[Error: ENOENT: no such file or directory, open '/Users/dev/local.test/pre-commit'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/dev/local.test/pre-commit'
}
```

Thank you

**Comment by ProjektGopher** [comment]
This is a super interesting case, thx for bringing it up! My suspicion is that I'm not set up yet to pass the commit message to the script. I'll have to look into this. I might not be able to get to it until about Thursday or Friday though. If you or someone else figures it out before then I'd be open to a PR though!

**Comment by encodiaweb** [comment]
Hi @ProjektGopher, any news about this feature?
Thank you very much

**Comment by ProjektGopher** [comment]
Hi @encodiaweb, no progress on this particular issue yet. Life has been super busy with a new kid and moving to a new house, all while still doing my client work.

If anyone has time to experiment with this one I'd be super grateful.

**Comment by davideprevosto** [comment]
> Life has been super busy with a new kid and moving to a new house, all while still doing my client work.

That's life 🎶 :-) 
I temporary switched to Husky, maybe someone will find the time to PR in the future. Thank you for your work.

**Comment by ProjektGopher** [comment]
From [the commitlint docs](https://commitlint.js.org/guides/local-setup.html#add-hook)
> To use commitlint you need to setup `commit-msg` hook (currently `pre-commit` hook is not supported)
