### ISSUE TITLE
The example from README.md is not working

### ISSUE THREAD

**Issue by alexmanase** [ProjektGopher/whisky#9]
I tried to run `whisky` in a new Laravel project but I got the following errors:

```bash
.git/hooks/pre-commit: line 3: In: command not found
.git/hooks/pre-commit: eval: line 5: syntax error near unexpected token `:'
.git/hooks/pre-commit: eval: line 5: `  in_array(): Argument #2 ($haystack) must be of type array, null given  '
```

I used the same code as in example.

**Comment by ProjektGopher** [comment]
@alexmanase I've committed @faissaloux's PR and released a patch. If you `composer update` this should be fixed.

**Comment by alexmanase** [comment]
```json
{
  "disabled": [],
  "hooks": {
    "pre-commit": [
      "./vendor/bin/pint && blade-formatter --write './resources/**/*.blade.php'"
    ],
    "pre-push": [
      "composer test:all"
    ]
  }
}
```

> have to re-add the staged files after they've been linted

I added them using `git add . && git commit -m 'wip'`.

> Thx for taking the time on making an issue, btw. This is super helpful for me.

You're welcome. I'm glad I can help.

**Comment by ProjektGopher** [comment]
Did you add and commit once, or did you do it twice? Here's what would need to happen:

1) save work, `git add . && git commit -m 'wip'`
2) pint and blade-formatter then run, and write the files
3) re-add those same files `git add . && git commit -m 'formatting'`
4) `git push`

Even though `pint` and `blade-formatter` are being run pre-commit, those new writes wont be staged for the actual commit. It might be better to add the `--test` flag to pint, and if there's a similar one for `blade-formatter` I'd do that as well. That way the commit fails, and forces you to pass _before_ the commit succeeds.

**Comment by alexmanase** [comment]
> That way the commit fails, and forces you to pass before the commit succeeds.

Now it makes more sense and it works as intended then. Shouldn't this be added in the documentation with explanation and example? 

>  and if there's a similar one for `blade-formatter` I'd do that as well

Unfortunately, there isn't.

Wouldn't be possible to stage the new writes from the hooks?

**Comment by ProjektGopher** [comment]
> Shouldn't this be added in the documentation with explanation and example?

I agree. I should add this.

> Wouldn't be possible to stage the new writes from the hooks?

Actually there is! In your project root, create a folder named `scripts`, and make a file named `git-add-staged` with the following contents:
```sh
#!/bin/bash

# Create a list of all staged files
# filter out deleted files
STAGED_FILES=$(git diff --name-only --cached --diff-filter=d)

# Pass that list of files to the following commands
if [ -n "$STAGED_FILES" ]; then
    # Re-stage the files that were just linted
    git add $STAGED_FILES
fi
```

This script will create a list of all the files that are already staged, and re-add them. That way you're not accidentally committing files that aren't ready for version control yet.

Then in your `whisky.json`, add a reference to that under the other command:
```json
{
  "disabled": [],
  "hooks": {
    "pre-commit": [
      "./vendor/bin/pint && blade-formatter --write './resources/**/*.blade.php'",
      "./scripts/git-add-staged"
    ],
    "pre-push": [
      "composer test:all"
    ]
  }
}
```

**OR** if you'd rather just add all files every time you can skip all that and just add `git add .` instead of `./scripts/git-add-staged`

**Comment by alexmanase** [comment]
That worked!

I've got the `Permission denied` error, but I fixed it with `chmod 755 ./scripts/git-add-staged `.

Thank you!
